version: "3"
services:
  credit-card-db:
    container_name: credit-card-db
    image: postgres:13.12-alpine
    environment:
      POSTGRES_DB: credit_card
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  credit-card-test-db:
    container_name: credit-card-test-db
    image: postgres:13.12-alpine
    environment:
      POSTGRES_DB: credit_card
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
